import "./globals.css";
import { Figtree } from "next/font/google";
import Sidebar from "@/components/Sidebar";
import SupabaseProvider from "@/providers/SupabaseProvider";
import UserProvider from "@/providers/UserProvider";
import ModalProvider from "@/providers/ModalProvider";
import ToasterProdiver from "@/providers/ToasterProdiver";
import getLatestAddresses from "@/actions/getLatestAddresses";

const font = Figtree({ subsets: ["latin"] });

export const metadata = {
  title: "Avva Supabase app",
  description: "Generated by create next app",
};

export const revalidate = 0;

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const latestAddresses = await getLatestAddresses();
  return (
    <html lang="en">
      <body className={font.className}>
        <ToasterProdiver />
        <SupabaseProvider>
          <UserProvider>
            <ModalProvider />
            <Sidebar addresses={latestAddresses}>{children}</Sidebar>
          </UserProvider>
        </SupabaseProvider>
      </body>
    </html>
  );
}
